pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/bhuvan-aradhya-l/Terraform.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform-AZ') {
                sh '''
                  terraform init -input=false
                '''
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('Terraform-AZ') {
                sh '''
                  terraform validate
                '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform-AZ') {
                sh '''
                  terraform plan -out=tfplan
                '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Terraform-AZ') {
                sh '''
                  terraform apply --auto-approve
                '''
                }
            }
        }
    }

    post {
        success {
            echo "Terraform pipeline executed successfully"
        }
        failure {
            echo "Terraform pipeline failed"
        }
    }
}
